name: Node.js Package

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/my-github-lerna
          always-auth: true
      - run: npm ci
      - run: npx lerna publish from-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}